#pragma once
#include "Common.h"
#include "Define.h"
#include <Wire.h>
	
	void W_begin(void);
	void W_end(void);
	void W_SetClock(void);
	void W_beginTransmission(void);
	void W_endTransmission(void);
	void W_requestFrom(void);
	void W_requestFrom1(void);
	void W_write(void);	
	void W_available(void);
	void W_read(void);	
	void W_peek(void);
	void W_flush(void);
	void W_onReceive(void);
	void W_onRequest(void);
	void WWinstaller(void);
